"""Re-index migration — recompute all embeddings for a new model.

Embedding spaces are immutable after init. Model change = full re-index.
This script:
  1. Reads all documents from the database
  2. Re-chunks clean_text
  3. Generates new embeddings with the current model
  4. Truncates document_chunks and re-inserts

Run: python -m trend_engine.scripts.reindex
"""

from __future__ import annotations

import asyncio
import logging

from trend_engine.config import get_settings
from trend_engine.db.client import SupabaseDB, close_http_client, init_http_client
from trend_engine.db.repository import TrendRepository
from trend_engine.ingestion.chunker import chunk_text
from trend_engine.ingestion.embedder import Embedder

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


async def reindex() -> None:
    """Full re-index: truncate chunks, re-chunk, re-embed, re-insert."""
    await init_http_client()
    settings = get_settings()
    db = SupabaseDB(settings)
    repo = TrendRepository(db)
    embedder = Embedder(settings)

    print(f"Re-indexing with model: {settings.embedding_model}")
    print(f"Embedding dim: {settings.embedding_dim}")

    # 1. Clear existing chunks (cascade will clear cluster_members)
    print("Clearing document_chunks...")
    await db.execute_sql("TRUNCATE document_chunks CASCADE")

    # 2. Clear clusters (derived state, will be regenerated by batch job)
    print("Clearing topic_clusters...")
    await db.execute_sql("TRUNCATE topic_clusters CASCADE")

    # 3. Read all documents
    docs = await db.select("documents")
    print(f"Found {len(docs)} documents to re-index")

    # 4. Re-chunk and re-embed each document
    total_chunks = 0
    for i, doc in enumerate(docs):
        doc_id = doc["id"]
        clean = doc["clean_text"]

        chunks = chunk_text(clean)
        if not chunks:
            continue

        try:
            embeddings = await embedder.embed_texts(chunks)
        except Exception as exc:
            logger.error(f"Embedding failed for doc {doc_id}: {exc}")
            continue

        chunk_rows = [
            {
                "document_id": doc_id,
                "chunk_text": ct,
                "embedding": str(emb),
            }
            for ct, emb in zip(chunks, embeddings)
        ]

        await repo.insert_chunks(chunk_rows)
        total_chunks += len(chunk_rows)

        if (i + 1) % 50 == 0:
            print(f"  Processed {i + 1}/{len(docs)} documents ({total_chunks} chunks)")

    print(f"Re-index complete: {len(docs)} documents, {total_chunks} chunks")
    await close_http_client()


if __name__ == "__main__":
    asyncio.run(reindex())
