"""Domain models and API schemas for the Trend Intelligence Engine."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


# ── Real-time Search Models ─────────────────────────────────────────


class SearchQueryType(str, Enum):
    """Type of focused sub-query."""

    RELEASE = "release"
    MIGRATION = "migration"
    PERFORMANCE = "performance"
    ROADMAP = "roadmap"
    ECOSYSTEM = "ecosystem"


class SearchQuery(BaseModel):
    """A focused sub-query generated by the query planner."""

    tag: str
    query_type: SearchQueryType
    query_text: str
    source_hint: str = ""


class SourceType(str, Enum):
    """Origin of a search result."""

    SERPER = "serper"
    GITHUB_RELEASES = "github_releases"
    GITHUB_SEARCH = "github_search"
    HACKER_NEWS = "hacker_news"


class SearchResult(BaseModel):
    """Raw result from a single source."""

    title: str = ""
    snippet: str = ""
    url: str = ""
    source: SourceType
    score: int = 0
    published_at: str = ""
    raw_data: dict = Field(default_factory=dict)


class SignalType(str, Enum):
    """Type of extracted signal."""

    VERSION = "version"
    DEPRECATION = "deprecation"
    PERFORMANCE = "performance"
    MIGRATION = "migration"
    FEATURE = "feature"
    BENCHMARK = "benchmark"
    GENERAL = "general"


class ExtractedSignal(BaseModel):
    """A structured fact extracted from a search result."""

    signal_type: SignalType = SignalType.GENERAL
    content: str = ""
    version: str = ""
    source_url: str = ""
    source_title: str = ""
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class RankedResult(BaseModel):
    """A search result after scoring, ranking, and deduplication."""

    result: SearchResult
    signals: list[ExtractedSignal] = Field(default_factory=list)
    freshness_score: float = 0.0
    authority_score: float = 0.0
    relevance_score: float = 0.0
    composite_score: float = 0.0


class TrendSourceInfo(BaseModel):
    """A single source with link and date."""

    title: str = ""
    url: str = ""
    source_type: str = ""
    date: str = ""
    score: int = 0


class TrendInsight(BaseModel):
    """Summarized trend insight from real-time search."""

    id: str = ""
    tag: str
    key_points: list[str] = Field(default_factory=list)
    momentum: str = ""
    risks: list[str] = Field(default_factory=list)
    opportunities: list[str] = Field(default_factory=list)
    direction: str = ""
    latest_version: str = ""
    version_info: str = ""
    sources: list[TrendSourceInfo] = Field(default_factory=list)
    sources_count: int = 0
    collected_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    embedding: list[float] | None = Field(default=None)


class RawTrendData(BaseModel):
    """Raw collected data before summarization."""

    tag: str
    serper_results: list[dict] = Field(default_factory=list)
    github_repos: list[dict] = Field(default_factory=list)
    hn_items: list[dict] = Field(default_factory=list)
    collected_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


# ── Domain Models ───────────────────────────────────────────────────


class Document(BaseModel):
    """Ingested document record."""

    id: UUID | None = None
    title: str
    source_name: str
    source_type: str  # rss | sitemap | release_notes | research
    published_at: datetime
    source_weight: float = Field(ge=0.0, le=1.0)
    raw_text: str
    clean_text: str
    content_hash: str
    inserted_at: datetime | None = None


class DocumentChunk(BaseModel):
    """Embedding-ready text chunk linked to a document."""

    id: UUID | None = None
    document_id: UUID
    chunk_text: str
    embedding: list[float] | None = None
    created_at: datetime | None = None


class TopicCluster(BaseModel):
    """Computed cluster with temporal metrics and scoring."""

    id: UUID | None = None
    label: str | None = None
    centroid_embedding: list[float]
    cluster_size: int
    weighted_doc_count_7: float
    weighted_doc_count_30: float
    weighted_doc_count_90: float
    growth_rate: float
    acceleration: float
    credibility_score: float
    source_diversity_score: float
    trend_score: float | None = None
    classification: str | None = None
    architecture_snapshot: dict | None = None
    market_stats: dict | None = None
    last_updated: datetime | None = None


class ClusterMember(BaseModel):
    """Link between a cluster and a document chunk."""

    cluster_id: UUID
    document_chunk_id: UUID
    assigned_at: datetime | None = None


# ── Source Configuration ────────────────────────────────────────────


class SourceConfig(BaseModel):
    """Deploy-time source definition."""

    name: str
    url: str
    source_type: str  # rss | sitemap | release_notes | research
    source_weight: float = Field(ge=0.0, le=1.0)
    enabled: bool = True


# ── API Request / Response Schemas ──────────────────────────────────


class SimilarQueryRequest(BaseModel):
    """POST /query/similar request body."""

    text: str
    top_k: int = Field(default=10, ge=1, le=100)


class SimilarResult(BaseModel):
    """Single result from similarity search."""

    chunk_id: str
    chunk_text: str
    document_id: str
    source_name: str
    published_at: datetime
    cluster_id: str | None = None
    cluster_label: str | None = None
    cluster_trend_score: float | None = None
    cluster_classification: str | None = None


class TrendSummary(BaseModel):
    """Item in GET /trends response."""

    cluster_id: str
    label: str | None
    classification: str | None
    trend_score: float | None
    growth_rate: float
    acceleration: float
    cluster_size: int
    credibility_score: float
    source_diversity_score: float
    representative_snippets: list[str]
    last_updated: datetime


class GrowthMetrics(BaseModel):
    """Temporal metrics block for technical view."""

    weighted_doc_count_7: float
    weighted_doc_count_30: float
    weighted_doc_count_90: float
    growth_rate: float
    acceleration: float


class SourceBreakdown(BaseModel):
    """Per-source stats in technical view."""

    source_name: str
    doc_count: int
    avg_source_weight: float


class TopDocument(BaseModel):
    """Document reference in technical view."""

    title: str
    url: str | None = None
    published_at: datetime


class TechnicalView(BaseModel):
    """GET /trends/{id}?view=technical response."""

    cluster_id: str
    label: str | None
    classification: str | None
    growth_metrics: GrowthMetrics
    architecture_snapshot: dict | None
    source_breakdown: list[SourceBreakdown]
    top_documents: list[TopDocument]


class MarketStats(BaseModel):
    """Executive market statistics."""

    adoption_velocity: str | None = None
    market_penetration: str | None = None
    community_health_score: float | None = None
    data_sources: list[str] = Field(default_factory=list)
    scraped_at: datetime | None = None


class BusinessSignals(BaseModel):
    """Executive business signals."""

    longevity_risk: str | None = None
    migration_urgency: str | None = None
    investment_signal: str | None = None


class ExecutiveView(BaseModel):
    """GET /trends/{id}?view=executive response."""

    cluster_id: str
    label: str | None
    classification: str | None
    trend_score: float | None
    architecture_snapshot: dict | None
    market_stats: MarketStats | None
    business_signals: BusinessSignals | None
    representative_snippets: list[str]


# ── AI Agent Context ────────────────────────────────────────────────


class RelatedTrend(BaseModel):
    """Single trend in agent context output."""

    label: str | None
    classification: str | None
    trend_score: float | None
    growth_rate: float
    acceleration: float
    architecture_snapshot: dict | None
    market_stats: dict | None
    source_diversity: float
    representative_snippets: list[str]
    top_sources: list[str]


class TrendContext(BaseModel):
    """Final structured output consumed by the AI agent."""

    query: str
    retrieved_at: datetime
    related_trends: list[RelatedTrend]
