"""Token optimizer - AGGRESSIVE code compression to reduce AI costs.

AGGRESSIVE Strategies:
1. Strip ALL comments (not just excessive ones)
2. Remove ALL standard imports
3. Remove ALL boilerplate/template code
4. Compress whitespace aggressively
5. Skip all test files
6. Truncate files aggressively
7. Remove empty lines within functions
"""

import re
from dataclasses import dataclass


@dataclass
class CompressionStats:
    """Statistics from code compression."""

    original_chars: int
    compressed_chars: int
    files_processed: int
    files_skipped: int

    @property
    def compression_ratio(self) -> float:
        """Return compression ratio (0-1, lower is better)."""
        if self.original_chars == 0:
            return 1.0
        return self.compressed_chars / self.original_chars

    @property
    def savings_percent(self) -> float:
        """Return percentage saved."""
        return (1 - self.compression_ratio) * 100


# Files to skip entirely
SKIP_FILE_PATTERNS = [
    r"\.d\.ts$",  # TypeScript declarations
    r"\.min\.(js|css)$",  # Minified
    r"package-lock\.json$",
    r"yarn\.lock$",
    r"pnpm-lock\.yaml$",
    r"\.generated\.",
    r"__generated__",
    r"\.snap$",  # Jest snapshots
    r"\.test\.",  # Test files
    r"\.spec\.",  # Spec files
    r"_test\.",  # Go test files
    r"test_",  # Python test files
    r"__tests__",  # Test directories
    r"__mocks__",  # Mock directories
    r"\.stories\.",  # Storybook
    r"\.md$",  # Markdown (readme, docs)
    r"license",  # License files
    r"changelog",  # Changelogs
    r"\.svg$",  # SVG files
    r"\.png$",  # Images
    r"\.jpg$",
    r"\.ico$",
    r"\.gif$",
    r"\.woff",  # Fonts
    r"\.ttf$",
    r"\.eot$",
    r"\.map$",  # Source maps
    r"node_modules/",
    r"vendor/",
    r"dist/",
    r"build/",
    r"\.next/",
    r"__pycache__/",
    r"\.git/",
]

# ALL imports to strip (very aggressive)
STRIP_IMPORT_PATTERNS = [
    # Python - strip ALL imports
    r"^import\s+\w+\s*$",
    r"^from\s+\w+\s+import\s+.+$",
    r"^from\s+\.\w*\s+import\s+.+$",
    # JavaScript/TypeScript - strip ALL imports  
    r"^import\s+.+from\s+['\"].+['\"];?\s*$",
    r"^import\s+['\"].+['\"];?\s*$",
    r"^import\s+\{[^}]+\}\s+from\s+['\"].+['\"];?\s*$",
    r"^const\s+\{[^}]+\}\s*=\s*require\(['\"].+['\"]\);?\s*$",
    r"^const\s+\w+\s*=\s*require\(['\"].+['\"]\);?\s*$",
    # Go imports
    r'^import\s+\([^)]+\)',
    r'^import\s+"[^"]+"',
]

# Boilerplate to remove
BOILERPLATE_PATTERNS = [
    # License headers (multi-line)
    r'/\*\*?[\s\S]*?(MIT|Apache|BSD|GPL|Copyright|License)[\s\S]*?\*/',
    r'"""[\s\S]*?(MIT|Apache|BSD|GPL|Copyright|License)[\s\S]*?"""',
    # Auto-generated markers
    r'//\s*(Auto-generated|Generated by|DO NOT EDIT|This file was)[^\n]*\n',
    r'#\s*(Auto-generated|Generated by|DO NOT EDIT|This file was)[^\n]*\n',
    # File headers
    r'//\s*(Created|Author|Date|Version):[^\n]*\n',
    r'#\s*(Created|Author|Date|Version):[^\n]*\n',
    # Empty docstrings
    r'"""[\s\n]*"""',
    r"'''[\s\n]*'''",
    # Shebang lines
    r'^#!.*\n',
    # Coding declarations
    r'^#.*coding[:=].*\n',
]

# ALL comments to strip
COMMENT_PATTERNS = {
    "py": [
        r'#[^\n]*\n',  # All # comments
        r'"""[^"]*"""',  # Docstrings (keep class/function ones)
    ],
    "js": [
        r'//[^\n]*\n',  # Single line
        r'/\*[\s\S]*?\*/',  # Multi-line
    ],
    "ts": [
        r'//[^\n]*\n',
        r'/\*[\s\S]*?\*/',
    ],
    "tsx": [
        r'//[^\n]*\n',
        r'/\*[\s\S]*?\*/',
    ],
    "jsx": [
        r'//[^\n]*\n',
        r'/\*[\s\S]*?\*/',
    ],
    "go": [
        r'//[^\n]*\n',
        r'/\*[\s\S]*?\*/',
    ],
    "rs": [
        r'//[^\n]*\n',
        r'/\*[\s\S]*?\*/',
    ],
    "java": [
        r'//[^\n]*\n',
        r'/\*[\s\S]*?\*/',
    ],
}


class TokenOptimizer:
    """AGGRESSIVE token optimizer to minimize AI costs."""

    def __init__(
        self,
        max_file_chars: int = 15000,  # Reduced from 30000
        max_total_chars: int = 800000,  # ~200K tokens total
    ) -> None:
        """Initialize optimizer.

        Args:
            max_file_chars: Max chars per file before truncation.
            max_total_chars: Max total chars across all files.
        """
        self.max_file_chars = max_file_chars
        self.max_total_chars = max_total_chars

    def optimize(
        self,
        file_contents: dict[str, str],
    ) -> tuple[dict[str, str], CompressionStats]:
        """Aggressively optimize all file contents.

        Args:
            file_contents: Dict of file paths to content.

        Returns:
            Tuple of (optimized contents, compression stats).
        """
        original_chars = sum(len(c) for c in file_contents.values())
        files_skipped = 0

        optimized: dict[str, str] = {}
        total_chars = 0

        # Sort files by importance (prioritize main code files)
        sorted_files = self._prioritize_files(file_contents)

        for path, content in sorted_files:
            # Skip unwanted files
            if self._should_skip_file(path):
                files_skipped += 1
                continue

            # Apply aggressive optimizations
            content = self._optimize_file(path, content)

            # Truncate if too large
            if len(content) > self.max_file_chars:
                content = self._truncate(content)

            # Stop if we've hit total limit
            if total_chars + len(content) > self.max_total_chars:
                files_skipped += 1
                continue

            if content.strip():
                optimized[path] = content
                total_chars += len(content)

        stats = CompressionStats(
            original_chars=original_chars,
            compressed_chars=total_chars,
            files_processed=len(optimized),
            files_skipped=files_skipped,
        )

        return optimized, stats

    def _prioritize_files(
        self, 
        file_contents: dict[str, str],
    ) -> list[tuple[str, str]]:
        """Sort files by importance."""
        def score(path: str) -> int:
            path_lower = path.lower()
            s = 0
            # High priority
            if "route" in path_lower or "api" in path_lower:
                s += 100
            if "model" in path_lower or "schema" in path_lower:
                s += 90
            if "service" in path_lower:
                s += 80
            if "controller" in path_lower or "handler" in path_lower:
                s += 70
            if "auth" in path_lower:
                s += 60
            if "config" in path_lower:
                s += 50
            # Low priority
            if "util" in path_lower or "helper" in path_lower:
                s -= 10
            if "type" in path_lower:
                s -= 20
            if "interface" in path_lower:
                s -= 20
            return s

        items = list(file_contents.items())
        items.sort(key=lambda x: score(x[0]), reverse=True)
        return items

    def _should_skip_file(self, path: str) -> bool:
        """Check if file should be skipped."""
        path_lower = path.lower()
        return any(re.search(p, path_lower) for p in SKIP_FILE_PATTERNS)

    def _optimize_file(self, path: str, content: str) -> str:
        """Aggressively optimize a single file."""
        ext = path.split(".")[-1].lower() if "." in path else ""

        # 1. Remove boilerplate
        for pattern in BOILERPLATE_PATTERNS:
            content = re.sub(pattern, "", content, flags=re.IGNORECASE | re.MULTILINE)

        # 2. Remove ALL imports
        lines = content.split("\n")
        filtered_lines = []
        for line in lines:
            skip = False
            for pattern in STRIP_IMPORT_PATTERNS:
                if re.match(pattern, line.strip(), re.MULTILINE):
                    skip = True
                    break
            if not skip:
                filtered_lines.append(line)
        content = "\n".join(filtered_lines)

        # 3. Remove comments (keep docstrings for context)
        if ext in COMMENT_PATTERNS:
            for pattern in COMMENT_PATTERNS[ext]:
                # Don't remove class/function docstrings entirely
                if '"""' in pattern or "'''" in pattern:
                    continue
                content = re.sub(pattern, "\n", content)

        # 4. Aggressive whitespace compression
        content = self._compress_whitespace(content)

        return content

    def _compress_whitespace(self, content: str) -> str:
        """Aggressively compress whitespace."""
        # Remove all blank lines
        content = re.sub(r'\n\s*\n', '\n', content)
        # Remove trailing whitespace
        content = re.sub(r'[ \t]+$', '', content, flags=re.MULTILINE)
        # Reduce indentation (4 spaces -> 2)
        lines = content.split('\n')
        compressed = []
        for line in lines:
            # Count leading spaces and halve them
            stripped = line.lstrip(' ')
            spaces = len(line) - len(stripped)
            new_indent = ' ' * (spaces // 2)
            compressed.append(new_indent + stripped)
        return '\n'.join(compressed)

    def _truncate(self, content: str) -> str:
        """Truncate file keeping most important parts."""
        # Keep first 60% (definitions) and last 20% (logic)
        keep_start = int(self.max_file_chars * 0.6)
        keep_end = int(self.max_file_chars * 0.2)
        
        return content[:keep_start] + "\n[...truncated...]\n" + content[-keep_end:]


def estimate_tokens(text: str) -> int:
    """Estimate token count (~4 chars per token)."""
    return len(text) // 4
