"""Data models for the agentic trend search pipeline.

Core models:
- SearchQuery: A focused sub-query for a technology tag
- SearchResult: Raw result from any source (Serper, GitHub, HN)
- ExtractedSignal: Structured fact extracted from a result
- RankedResult: Scored and deduplicated result
- TrendInsight: Final synthesized insight (stored in RAG)
- TrendSourceInfo: Source citation with link and date
- RawTrendData: Intermediate collected data before synthesis
"""

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, Field


class SearchQueryType(str, Enum):
    """Type of focused sub-query."""

    RELEASE = "release"
    MIGRATION = "migration"
    PERFORMANCE = "performance"
    ROADMAP = "roadmap"
    ECOSYSTEM = "ecosystem"


class SearchQuery(BaseModel):
    """A focused sub-query generated by the query planner."""

    tag: str
    query_type: SearchQueryType
    query_text: str
    source_hint: str = ""  # "serper", "github", "hn", or "" for all


class SourceType(str, Enum):
    """Origin of a search result."""

    SERPER = "serper"
    GITHUB_RELEASES = "github_releases"
    GITHUB_SEARCH = "github_search"
    HACKER_NEWS = "hacker_news"


class SearchResult(BaseModel):
    """Raw result from a single source."""

    title: str = ""
    snippet: str = ""
    url: str = ""
    source: SourceType
    score: int = 0  # Upvotes, stars, or search position
    published_at: str = ""  # ISO date string or empty
    raw_data: dict = Field(default_factory=dict)


class SignalType(str, Enum):
    """Type of extracted signal."""

    VERSION = "version"
    DEPRECATION = "deprecation"
    PERFORMANCE = "performance"
    MIGRATION = "migration"
    FEATURE = "feature"
    BENCHMARK = "benchmark"
    GENERAL = "general"


class ExtractedSignal(BaseModel):
    """A structured fact extracted from a search result."""

    signal_type: SignalType = SignalType.GENERAL
    content: str = ""
    version: str = ""  # Extracted version number if applicable
    source_url: str = ""
    source_title: str = ""
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class RankedResult(BaseModel):
    """A search result after scoring, ranking, and deduplication."""

    result: SearchResult
    signals: list[ExtractedSignal] = Field(default_factory=list)
    freshness_score: float = 0.0
    authority_score: float = 0.0
    relevance_score: float = 0.0
    composite_score: float = 0.0


# --- Models used by orchestrator (backward-compatible) ---


class TrendSourceInfo(BaseModel):
    """A single source with link and date."""

    title: str = ""
    url: str = ""
    source_type: str = ""  # "web", "github", "hn"
    date: str = ""
    score: int = 0


class TrendInsight(BaseModel):
    """Summarized trend insight for RAG storage.

    Includes source links, dates, and version info.
    """

    id: str = ""
    tag: str
    key_points: list[str] = Field(
        default_factory=list,
        description="Max 5-7 bullet points summarizing the trend",
    )
    momentum: str = ""  # rising, stable, declining
    risks: list[str] = Field(
        default_factory=list,
        description="Max 3 key risks",
    )
    opportunities: list[str] = Field(
        default_factory=list,
        description="Max 3 key opportunities",
    )
    direction: str = ""  # Where the tech is heading
    latest_version: str = ""
    version_info: str = ""  # Brief version change notes
    sources: list[TrendSourceInfo] = Field(default_factory=list)
    sources_count: int = 0
    collected_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )
    embedding: list[float] | None = Field(default=None)


class RawTrendData(BaseModel):
    """Raw collected data before summarization."""

    tag: str
    serper_results: list[dict] = Field(default_factory=list)
    github_repos: list[dict] = Field(default_factory=list)
    hn_items: list[dict] = Field(default_factory=list)
    collected_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )
